### ISSUE TITLE
#1

### ISSUE THREAD

**Issue by nikoloz14** [freeuni-sdp/iot-router#1]
როუტერმა როგორ უნდა გაარჩიოს, რომელია სახლის პატრონის MAC მისამართი?

**Comment by gkiko** [comment]
ჩათვალე რომ რა მაკებიც შენთან მოხვდება ყველა ადამიანს ეკუთვნის

**Comment by nikoloz14** [comment]
ანუ, 1 მაინც MAC თუა ესეიგი პატრონი სახლშია?

**Comment by gkiko** [comment]
კი

**Comment by nikoloz14** [comment]
გასაგებია, მადლობა!
