### ISSUE TITLE
Add CORS headers for browser

### ISSUE THREAD

**Issue by ggham** [freeuni-sdp/iot-router#3]
bowser-იდან მიღებული რექუესთის დროს(ან ნებისმიერი რექუესთის დროს, არაფერი დაშავდება) რესფონსის ჰედერებში უნდა იყოს ველები:
"Access-Control-Allow-Origin: *"
"Access-Control-Allow-Methods: POST, GET, PUT, DELETE, OPTIONS"
 "Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept"
იმისთვის, რო ბრაუზერმა დაამუშავოს მიღებული response.

**Comment by nikoloz14** [comment]
e4837d0498978adac6e162fe6a96bc68a8f9409f
