### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by ggham** [freeuni-sdp/iot-router#4]
a1bc00fb-4724-476a-a553-d65d2c1bac0e ეს არის house-registry-დან წამოღებული სახლის id. და როცა დივაისების სიას ვითხოვ, ან owner at home-ს, ამ სახლის აიდიზე, 404 ბრუნდება სერვისიდან.

**Comment by nikoloz14** [comment]
e4837d0498978adac6e162fe6a96bc68a8f9409f
